development: &default
  adapter: postgresql
  database: administrate-prototype_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000
  username: <%= ENV.fetch('PGUSER') { 'postgres' } %>
  password: <%= ENV.fetch('PGPASSWORD') { 'postgres' } %>
  host: <%= ENV.fetch('PGHOST') { 'db' } %>
  port: <%= ENV.fetch('PGPORT') { 5432 } %>

test:
  <<: *default
  database: administrate-prototype_test
