development: &default
  adapter: postgresql
  database: administrate-prototype_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000
  username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>
  host: <%= ENV.fetch('DB_HOST') { 'db' } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>

test:
  <<: *default
  database: administrate-prototype_test
